# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "infinite-product-options"
client_id = "46ec9c3dd8792f6780c371e936ee0bf2"
application_url = "https://infinity-variation.onrender.com"
embedded = true

[access_scopes]
scopes = "write_products,read_products,write_themes,read_themes"

[auth]
redirect_urls = [
  "https://infinity-variation.onrender.com/auth/callback",
  "https://infinity-variation.onrender.com/auth/shopify/callback",
  "https://infinity-variation.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
